# Generated by Django 2.2 on 2020-09-18 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='updated_aT',
            new_name='updated_at',
        ),
    ]
